// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-bQS2ZZ1-z7sdgVmfL0MwRFNZGqY8AgM',
    appId: '1:1032595942344:web:0c2d008c85f31fa5f5eefd',
    messagingSenderId: '1032595942344',
    projectId: 'hotel-management-2b186',
    authDomain: 'hotel-management-2b186.firebaseapp.com',
    storageBucket: 'hotel-management-2b186.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoNhQyKsI471w6Cm0XCpIpDhfDL-K6Uxw',
    appId: '1:1032595942344:android:8835a2239eb9ce0af5eefd',
    messagingSenderId: '1032595942344',
    projectId: 'hotel-management-2b186',
    storageBucket: 'hotel-management-2b186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkPrYGIOHozJOsFaE8SPKHHb237Rb7ycs',
    appId: '1:1032595942344:ios:72661d605ef89d20f5eefd',
    messagingSenderId: '1032595942344',
    projectId: 'hotel-management-2b186',
    storageBucket: 'hotel-management-2b186.appspot.com',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkPrYGIOHozJOsFaE8SPKHHb237Rb7ycs',
    appId: '1:1032595942344:ios:9d9b39874e38cc8af5eefd',
    messagingSenderId: '1032595942344',
    projectId: 'hotel-management-2b186',
    storageBucket: 'hotel-management-2b186.appspot.com',
    iosBundleId: 'com.example.hotel.RunnerTests',
  );
}
